### ISSUE TITLE
DpsWithReconnect Composites should forward punctuation

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.dps#72]
DpsWithReconnect Composites should forward punctuation. Currently they don't handle punctuation.

**Comment by brandtol** [comment]
This problem also affects the final punctuations. They do not got through the composite, because the second input port (the metrics one). I would suggest to use 
```
				onPunct In :
				{
					submit( currentPunct() , Out);
				}
```
Or maybe we can get rid of the aggregate operator and do tumbling aggregations directly in the composite operator, to avoid the loopback.

**Comment by Alex-Cook4** [comment]
@brandtol I agree with the first approach is good for handling both window/final punctuations. 

I don't think I follow the issue with the aggregate operator (having sliding metrics were a key requirement). 
The docs state: 
> Sending final punctuation to an output port effectively closes the port. The operator discards all subsequent tuples and punctuation submitted to that port.

So if I understand correctly, we would submit a final punct to the output port of the operator/composite, thereby completing the stream. So in that case, the aggregate isn't an issue, right?

**Comment by brandtol** [comment]
In my test it worked that way. I am not sure if we also want to forward punctuations to the aggregate operator. For the final punct , it was not neccessary.
