### ISSUE TITLE
Fix log levels of outputs

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.dps#83]
There are several messages that are logged with the wrong level.
Also there are a few prints to stdout, which need to be removed.

**Comment by nmwaara** [comment]
Here are a couple of log statements that are currently ERROR level, could probably be reduced to DEBUG or INFO level...
[https://github.com/IBMStreams/streamsx.dps/blob/a485d1adf6c26940f8736833b693c68005030b11/com.ibm.streamsx.dps/impl/src/DistributedProcessStore.cpp#L110](https://github.com/IBMStreams/streamsx.dps/blob/a485d1adf6c26940f8736833b693c68005030b11/com.ibm.streamsx.dps/impl/src/DistributedProcessStore.cpp#L110)
[https://github.com/IBMStreams/streamsx.dps/blob/a485d1adf6c26940f8736833b693c68005030b11/com.ibm.streamsx.dps/impl/src/DistributedProcessStore.cpp#L228](https://github.com/IBMStreams/streamsx.dps/blob/a485d1adf6c26940f8736833b693c68005030b11/com.ibm.streamsx.dps/impl/src/DistributedProcessStore.cpp#L228)

These are the only two I've found so far (based off a support case) but there may be others that need updating too. I can take another look to see if I can find any more specifics.

**Comment by nysenthil** [comment]
Those messages are there for a specific reason since 2014. Those messages get written to the PE log file only once when a PE starts. They are simply informational messages and not error messages. Since they are logged at the error trace level, it carries a prefix ERROR which causes  confusion to those who don’t know much about what the individual IBM Streams tracing fields mean. Those messages must stay for us to know whether the DPS initialization happened correctly behind the scenes or not. Otherwise,  we will not know what happened during the Redis initialization that is done only once when a PE starts up.

**Comment by joergboe** [comment]
Probably those one-time (configuration) messages should be printed out to the PE-console. In PE-log-files they soon disappear due to the log rotation.
